package com.myteam.jbpm_6456_reproducer;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DataObject implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String name;

	public DataObject() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public DataObject(java.lang.String name) {
		this.name = name;
	}

}